name: 'YOLO & CO'
favicon: null
layout_spectrum: 0.49684
typography_spectrum: 0.24201
title: You Only Live Once
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdee5'
    - '#aea9a3'
    - '#7c7c7c'
    - '#605e5f'
    - '#444247'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.012614532373845577
purpose: []
