typography_spectrum: 0.24201
color:
  brandColors:
    - '#cfdee5'
    - '#aea9a3'
    - '#7c7c7c'
    - '#605e5f'
    - '#444247'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: YOLO & CO
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: ed9d59c6-cb37-4b48-8b31-a203832c91e7
    url: 2016-04-19-ed9d59c6-cb37-4b48-8b31-a203832c91e7.html
    name: about
    type: content
favicon: null
title: You Only Live Once
purpose: []
